#!/bin/bash
cd ./BUREAU
exchange=$(./solution)
cd ..
echo "$exchange"
time=$1
script="$2"
flag="loud"
cmd="$script $3 $4 $5 $6 $7 $8"
TOOLS=./TOOLS
if [[ "$2" == "silent" ]]; then
	flag="silent"
	script="$3"
	cmd="$script $4 $5 $6 $7 $8 $9"
fi

totalWaitTime=$("$TOOLS/estimateTime.sh" $time)

echo -e
echo  "$script has begun."
echo  "It will continue in $totalWaitTime"
echo -e

#$cmd

status=1
errStatus=0



sub() (
	hesitate() {
		state=true

		while $state; do
			br=$(cat "$exchange/DATA/break")
			if [[ $br -eq 1 ]]; then
				state=false
			fi
		done
	}
	until false; do
		if [[ $flag == "silent" ]]; then
			$cmd
		else
			echo -e
			echo  "$script has begun."
			echo  "It will continue in $totalWaitTime"
			echo -e
			$cmd
		fi
		status=$?
		
		if [[ $status -ne 0  ]]; then
			echo "ATTENTION: $script is not working at the moment."
			sleep 5
		fi
		sleep $time
		hesitate
	done
)

sub &

# //export loop to different wrapper 
