#!/bin/bash

clear
../header
echo -e
echo ____________________________________________
echo -e
echo ------------- BUREAU Starting --------------
echo ____________________________________________
echo -e
