#!/bin/bash

exchange=$1
network=$2
status=1
errStatus=0
relPath=../SOLUTIONS/networks/$2/

if [[ -z $exchange ]]; then
	echo "Error: Missing exchange."
	status=0
	errStatus=1
fi

if [[ -z $network ]]; then
	echo "Error: Missing network."
	status=0
	errStatus=2
fi

exRelPath=$relPath/$exchange

./header


until [ $status -eq 0 ]; do

	#&& ./composeFlashLoans.sh $network \
	./genConstants.sh "$exRelPath" "$network" $1 \
	&& ../TOOLS/syncNetworks.sh \
	&& ./establish.sh $1 $network
	status=$?
	
	if [[ $status -ne 0  ]]; then
		sleep 10
		./header
	fi

done

if [[ $status -eq 0 && $errStatus -eq 0 ]]; then
    echo ____________________________________________
	echo -e
	echo 'The Bureaucracy is finished.'
    echo ____________________________________________
	echo -e
fi
