#!/bin/bash

network=250
source=$1
srcDec=18
dest=$2
destDec=18
amount=$3
#side=BUY
exchange=paraswap
script=../../../exchanges/API/QUERY/PAIR/$exchange
#echo network: $network
#echo source: $source
#echo srcDec: $srcDec
#echo dest: $dest
#echo destDesc: $destDec
#echo acmount: $amount
#echo side: $side
#echo exchange $exchange
#echo -e
#echo -e --------------------------------
#echo -e
#dir $script
bash $script $network $source $srcDec $dest $destDec $amount $side
#echo -e
#echo -e --------------------------------
#echo -e
