#!/bin/bash
exchange=$1
time=$2
script="$3"
flag="loud"
cmd="$script $4 $5 $6 $7 $8 $9 ${10}"
TOOLS=./../TOOLS
if [[ "$3" == "silent" ]]; then
	flag="silent"
	script="$4"
	cmd="$script $5 $6 $7 $8 $9 ${10} ${11}"
fi

totalWaitTime=$("$TOOLS/estimateTime.sh" $time)

echo -e
echo  "$script has begun."
echo  "It will continue in $totalWaitTime"
echo -e

#$cmd

status=1
errStatus=0



sub() (
	hesitate() {
		state=true

		while $state; do
			br=$(cat "$exchange/DATA/break")
			ps=$(cat "$exchange/DATA/pause")
			if [[ $ps -gt 0 ]]; then
				state=true
			elif [[ $br -eq 1 ]]; then
				state=false
			fi
		done
	}
	until false; do
		sleep $time
		if [[ $flag == "silent" ]]; then
			$cmd &
		else
			echo -e
			echo  "$script has begun."
			echo  "It will continue in $totalWaitTime"
			echo -e
			$cmd
		fi
		status=$?
		
		if [[ $status -ne 0  ]]; then
			echo "ATTENTION: $script is not working at the moment."
			sleep 5
		fi
		hesitate
	done
)

sub & 

# //export loop to different wrapper 
