#!/bin/bash
time=$1
script="$2"
flag="loud"
cmd="$script $3 $4 $5 $6 $7"
if [[ "$2" == "silent" ]]; then
	flag="silent"
	script="$3"
	cmd="$script $4 $5 $6 $7 $8"
fi

totalWaitTime=$(./../TOOLS/estimateTime.sh $time)

echo -e
echo  "$script has begun."
echo  "It will continue in $totalWaitTime"
echo -e

$cmd

status=1
errStatus=0

sub() {
until false; do
	sleep $time
	if [[ $flag == "silent" ]]; then
		$cmd &
	else
		echo -e
		echo  "$script has begun."
		echo  "It will continue in $totalWaitTime"
		echo -e
		$cmd
	fi
	status=$?
	
	if [[ $status -ne 0  ]]; then
		echo "ATTENTION: $script is not working at the moment."
		sleep 5
	fi

done
}

sub & 

# //export loop to different wrapper 