#!/bin/bash
time=$1
script="$2"
flag="loud"
cmd="$script $3 $4 $5 $6 $7"
if [[ "$2" == "silent" ]]; then
	flag="silent"
	script="$3"
	cmd="$script $4 $5 $6 $7 $8"
fi

compare() (IFS=" "
  exec awk "BEGIN{if (!($*)) exit(1)}"
)
if [ "$time" -eq 0 ]; then
	totalWaitTime="no time."
	flag="silent"
elif compare "$time < 1"; then
	totalWaitTime=$(echo "$time * 1000" | bc -l)
	totalWaitTime="$totalWaitTime ms"
	flag="silent"
elif [ "$time" -lt 60 ]; then
	totalWaitTime="$time seconds"
elif [ "$time" -lt 3600 ]; then
	totalWaitTime=$(echo "$time / 60" | bc -l)
	totalWaitTime="$totalWaitTime minutes"
elif [ "$time" -lt 86400 ]; then
	totalWaitTime=$(echo "$time / 3600" | bc -l)
	totalWaitTime="$totalWaitTime hours"
elif [ "$time" -lt 604800 ]; then
	totalWaitTime=$(echo "$time / 86400" | bc -l)
	totalWaitTime="$totalWaitTime days"
elif [ "$time" -lt 2592000 ]; then
	totalWaitTime=$(echo "$time / 604800" | bc -l)
	totalWaitTime="$totalWaitTime weeks"
elif [ "$time" -lt 31536000 ]; then
	totalWaitTime=$(echo "$time / 2592000" | bc -l)
	totalWaitTime="$totalWaitTime months"
else
	totalWaitTime=$(echo "$time / 31536000" | bc -l)
	totalWaitTime="$totalWaitTime years"
fi

echo -e
echo  "$script has begun."
echo  "It will continue in $totalWaitTime"
echo -e

$cmd

status=1
errStatus=0

sub() {
until false; do
	sleep $time
	if [[ $flag == "silent" ]]; then
		$cmd &
	else
		echo -e
		echo  "$script has begun."
		echo  "It will continue in $totalWaitTime"
		echo -e
		$cmd
	fi
	status=$?
	
	if [[ $status -ne 0  ]]; then
		echo "ATTENTION: $script is not working at the moment."
		sleep 5
	fi

done
}

sub & 

# //export loop to different wrapper 