#!/bin/bash

exchange=$1
network=$2
vol=$3
status=1
errStatus=0
relPath=../SOLUTIONS/networks/$2/

if [[ -z $exchange ]]; then
	echo "Error: Missing exchange."
	status=0
	errStatus=1
fi

if [[ -z $network ]]; then
	echo "Error: Missing network."
	status=0
	errStatus=2
fi

exchange=$relPath/$exchange
mrc=$(cat "$exchange/DATA/mrc")
spread=$(cat "$exchange/DATA/spread")
trailLimit=$(cat "$exchange/DATA/trailLimit")

if [[ -z $vol ]]; then
	vol=$(cat "$exchange/DATA/volatility")
fi

./header

until [ $status -eq 0 ]; do
	../TOOLS/switch.sh $exchange 1
	sleep .01
	# gcc genPairs.c -o genPairs.o \
	# valgrind ./genPairs.o $exchange'/DATA/'$vol'VolTokens.cf' $exchange'/DATA/'$vol'CTV.srls' $exchange'/DATA/'$vol'CTVBinaries.srls'
	./continue $exchange 500 silent ./interlace.o $exchange'/DATA/'$vol'CTVBinaries.srls' $exchange'/DATA/'$vol'CTVInterlacedBinaries.srls' $spread
	#&& ./hyperHash.o $exchange'/DATA/'$vol'CTV.srls' $exchange'/DATA/'$vol'CTVInterlacedBinaries.srls'
	./continue $exchange 0 ./deployBinaries.sh $exchange $exchange"/DATA/"$vol"CTVInterlacedBinaries.srls" $vol 
	./again $exchange .0375 silent ./assemble.sh $1 $network $vol
	status=$?
	
	if [[ $status -ne 0  ]]; then
		sleep 5
		./header
	fi

done

if [[ $status -eq 0 && $errStatus -eq 0 ]]; then
	echo -e
	echo 'Successfully constructed arbitrage pairs for the '$exchange' contracts on '$2'.'
	echo -e
	echo "Get excited bitch, we're about to be rich!"
	echo -e
fi

#loop hiden
#loop shown
#loop loops the process over and over again with a wait time
#hiden means the process within has a & flag added
