#!/bin/bash

exchange=$1
network=$2
status=1
errStatus=0
relPath=../SOLUTIONS/networks/$2/

if [[ -z $exchange ]]; then
	echo "Error: Missing exchange."
	status=0
	errStatus=1
fi

if [[ -z $network ]]; then
	echo "Error: Missing network."
	status=0
	errStatus=2
fi

exchange=$relPath/$exchange

./header

until [ $status -eq 0 ]; do
	./genBinaries.o $exchange'/DATA/hiVolTokens.cf' $exchange'/DATA/hiCTV.srls' $exchange'/DATA/hiCTVBinaries.srls'\
	&& ./deployBinaries.sh $exchange $exchange'/DATA/hiCTVBinaries.srls' \
	&& ./groupQuotes.sh $exchange $network
	#./getPairs.o $exchange'/DATA/hiVolTokens.cf' $exchange'/DATA/hiCTV.srls' $exchange'/DATA/hiCTVBinaries.srls'\
	#./hyperHash.o $exchange'/DATA/hiCTV.srls' $exchange'/DATA/hiCTVBinaries.srls' \
	#&& ./hyperHash.o $exchange'/DATA/hiCTV.srls' $exchange'/DATA/hiCTVBinaries.srls' \
	#&& ./getPairs.o $exchange'/DATA/loVolTokens.cf' $exchange'/DATA/loCTV.srls' $exchange'/DATA/loCTVBinaries.srls'\
	#&& ./hyperHash.o $exchange'/DATA/loCTV.srls' $exchange'/DATA/loCTVBinaries.srls'
	status=$?
	
	if [[ $status -ne 0  ]]; then
		sleep 5
		./header
	fi

done

if [[ $status -eq 0 && $errStatus -eq 0 ]]; then
	echo -e
	echo 'Successfully constructed arbitrage pairs for the '$exchange' contracts on '$2'.'
	echo -e
	echo "Get excited bitch, we're about to be rich!"
	echo -e
fi
