#!/bin/bash

exchange=$1
network=$2
vol=$3
status=1
errStatus=0
relPath=../SOLUTIONS/networks/$2/

if [[ -z $exchange ]]; then
	echo "Error: Missing exchange."
	status=0
	errStatus=1
fi

if [[ -z $network ]]; then
	echo "Error: Missing network."
	status=0
	errStatus=2
fi

exchange=$relPath/$exchange

./header

until [ $status -eq 0 ]; do
	# ./continue 86400 ./genPairs.o $exchange'/DATA/hiVolTokens.cf' $exchange'/DATA/hiCTV.srls' $exchange'/DATA/hiCTVBinaries.srls'\
	# && ./continue 0 ./hyperHash.o $exchange'/DATA/hiCTV.srls' $exchange'/DATA/hiCTVBinaries.srls' \
	# && ./continue 18000 ./deployBinaries.sh $exchange $exchange'/DATA/hiCTVBinaries.srls' \
	# ./continue 2 ./groupQuotes.sh $exchange $network
	# ./continue 2 node ./filterQuotes.js $exchange $network "high"

	
	./genPairs.o $exchange'/DATA/'$vol'VolTokens.cf' $exchange'/DATA/'$vol'CTV.srls' $exchange'/DATA/'$vol'CTVBinaries.srls'\
	&& ./hyperHash.o $exchange'/DATA/'$vol'CTV.srls' $exchange'/DATA/'$vol'CTVBinaries.srls' \
	./deployBinaries.sh $exchange $exchange"/DATA/"$vol"CTVBinaries.srls" $vol \
	&& ./groupQuotes.sh $exchange $network $vol \
	&& node ./filterQuotes.js $exchange $network $vol
	status=$?
	
	if [[ $status -ne 0  ]]; then
		sleep 5
		./header
	fi

done

if [[ $status -eq 0 && $errStatus -eq 0 ]]; then
	echo -e
	echo 'Successfully constructed arbitrage pairs for the '$exchange' contracts on '$2'.'
	echo -e
	echo "Get excited bitch, we're about to be rich!"
	echo -e
fi

#loop hiden
#loop shown
#loop loops the process over and over again with a wait time
#hiden means the process within has a & flag added