#!/bin/bash

network=250
relPathA=../SOLUTIONS/networks/fantom/paraswap
relPathB=../SOLUTIONS/exchanges
file=$relPathA/DATA/tokenList.json
script=$relPathB/API/QUERY/TOKENLIST/paraswap

$script $network $file
