#!/bin/bash

network=$1
source=$2
srcDec=$3
dest=$4
destDec=$5
amount=$6
side=$7
#link="https://apiv5.paraswap.io/prices?network=${network}&srcToken=${source}&srcDecimals=${srcDec}&destToken=${dest}&destDecimals=${destDec}&amount=${amount}&side=${side}" # removed side to allow the api to provide best side.
link="https://apiv5.paraswap.io/prices?network=${network}&srcToken=${source}&srcDecimals=${srcDec}&destToken=${dest}&destDecimals=${destDec}&amount=${amount}"
curl $link
