#!/bin/bash

exchange=$1
network=$2
status=1
errStatus=0
relPath=../SOLUTIONS/networks/$2/

if [[ -z $exchange ]]; then
	echo "Error: Missing exchange."
	status=0
	errStatus=1
fi

if [[ -z $network ]]; then
	echo "Error: Missing network."
	status=0
	errStatus=2
fi

exRelPath=$relPath/$exchange

./header

networkID=$(cat $exRelPath/DATA/name)
chainID=$(cat $exRelPath/DATA/chainID)

until [ $status -eq 0 ]; do

	./$exRelPath/API/QUERY/TOKENLIST/aux $exchange $network $chainID \
	&& bun run ./parseList.js $exRelPath \
	&& ./fetchTokens.sh $exRelPath $networkID 1.25 \
	&& bun run ./cleanList.js $exRelPath \
	&& bun run ./calcTokens.js $exRelPath $network \
	&& bun run ./formatTokens.js $exRelPath $network
	status=$?
	
	if [[ $status -ne 0  ]]; then
		sleep 10
		./header
	fi

done

if [[ $status -eq 0 && $errStatus -eq 0 ]]; then
	echo -e
	echo 'Successfully primed tokens for the '$exchange' architecture on '$2'.'
	echo -e
	echo "Get excited bitch, we're about to be rich!"
	echo -e
fi
